"""empty message

Revision ID: 328f8712d8f6
Revises: 7baaac092698
Create Date: 2026-06-02 01:42:14.510202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328f8712d8f6'
down_revision = '7baaac092698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_spot_favorite', ['user_id', 'spot_id'])

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_spot_rating', ['user_id', 'spot_id'])

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.create_unique_constraint('unique_user_spot_view', ['user_id', 'spot_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_spot_view', type_='unique')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_spot_rating', type_='unique')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_spot_favorite', type_='unique')

    # ### end Alembic commands ###
